import type { Form } from './formTypes';

export const initialState: Form = {
  _id: '',
  nome: '',
  email: '',
  matricula: '',
  data_nascimento: '1970-01-01T00:00:00Z',
  curso: '',
  ano_ingresso: '',
  sexo: '',
  bolsista: '',
  frequencia_RU: '',
  tipo_refeicao_RU: '',
  nivel_fisico: '',
  peso_ideal: false,
  alergias: {
    alergia_gluten: false,
    intolerancia_lactose: false,
    proteina_leite_vaca: false,
    outras_alergias: '',
  },
  vegano_vegetariano: '',
  adiciona_sal: false,
  utiliza_oleo_composto: false,
  consome_bebida_alcoolica: '',
  tabagista: false,
  patologias: {
    doenca_cardiovascular: false,
    hipertensao_arterial: false,
    obesidade: false,
    dislipidemias: false,
    doenca_arterial_coronariana: false,
    diabetes: false,
    outras_patologias: '',
  },
  patologias_familia: {
    fam_doenca_cardiovascular: false,
    fam_hipertensao: false,
    fam_obesidade: false,
    fam_dislipidemias: false,
    fam_doenca_arterial_coronariana: false,
    fam_diabetes: false,
    patologias_familia_outras: '',
  },
  medicamento_continuo: '',
  avaliacao_RU: {
    aroma: 'Regular',
    coloracao_cardapio: 'Regular',
    textura_preparacao: 'Regular',
    sabor_preparacao: 'Regular',
    avaliacao_geral: 'Regular',
  },
  melhorias_RU: {
    cardapio: false,
    melhoria_sabor_preparacao: false,
    opcao_vegetariana: false,
    estrutura_fisica: false,
    tempo_fila: false,
    preco_ticket: false,
    melhoria_outros: '',
  },
};
